### ISSUE TITLE
New Distribution Practice: Exclude unnesessary files from npm publish 

### ISSUE THREAD

**Issue by m-sureshraj** [lirantal/nodejs-cli-apps-best-practices#50]
I think this is an important practice to keep the published package size small. Sometimes package authors accidentally include their development configuration, spec files, etc. part of the published package. [I've done it once](https://github.com/m-sureshraj/jenni/issues/13) 🙆‍♂️

For more details on this topic - https://medium.com/@nodejs/publishing-npm-packages-c4c615a0fc6b

**Comment by lirantal** [comment]
you're referring to the files array, right? yes definitely!
let's add it on the last section - 7 - which deals with development guidelines WDYT?

**Comment by m-sureshraj** [comment]
> you're referring to the files array, right?

Yes.

> let's add it on the last section - 7

I feel this practice will provide more value under the distribution section. 
Because in the development, we rarely pack the application.

**Comment by lirantal** [comment]
but making use of the files array in itself is a development practice, rather than an overall paradigm. Since there's already a related bullet there (2.1 Prefer a small dependency footprint), I'm thinking we can either add it as a new one in section 7 and refer to 2.1, or add it as an example in 2.1.

What do you think?

**Comment by m-sureshraj** [comment]
Hmm, make sense. I prefer the first option. (`add it as a new one in section 7 and refer to 2.1`)

**Comment by lirantal** [comment]
Sounds good to me.
