### ISSUE TITLE
remove 2.3 Cleanup configuration files chapter as it does not work since npm v7

### ISSUE THREAD

**Issue by blzsaa** [lirantal/nodejs-cli-apps-best-practices#83]
As written in https://docs.npmjs.com/cli/v8/using-npm/scripts#a-note-on-a-lack-of-npm-uninstall-scripts the uninstall lifecycle scripts are not implemented and will not function since v7. Due to that chapter `2.3 Cleanup configuration files` chapter should be removed as it does not work since npm v7

According to https://nodejs.org/en/about/releases/
-  node 14 the maintenance LTS, which comes with npm v6, is supported until 2023-04-30.
-  node 16 the active LTS, which comes with npm v8, is supported until 2024-04-30.

**Comment by lirantal** [comment]
Thanks for bringing it up, you're right!

@blzsaa the overall cleanup guideline still holds, regardless of what the implementation detail is.
How about that we update the last line in that bullet (here: https://github.com/lirantal/nodejs-cli-apps-best-practices/blob/main/README.md?plain=1#L373) so that it removes that line, and instead add a note that while this was supported in v6 it doesn't anymore since v7 (the lifecycle hook I mean), and advise that due to the lack of the npm package manager providing this event, we recommend that the CLI tool includes a `prune` or `cleanup` that is advised for users to run before the CLI is uninstalled.

WDYT and would you want to raise a PR with the above changes?

**Comment by blzsaa** [comment]
I created a pull request please review it and update it if necessary,
